export const incomeGeneral = {
  periodo: "January - April 2026",
  personaConMayorIngreso: "Lucia Fernandez",
  personaConMenorIngreso: "Sofia Herrera",
  promedioPorPersona: 4612.5,
  titulo: "Income generated by person",
  totalIngresos: 18450,
} as const;
